### ISSUE TITLE
grad doesn't work on trivial identity

### ISSUE THREAD

**Issue by tscode** [denizyuret/AutoGrad.jl#101]
I am on the official julia 1.0.1 release with all packages up-to-date.
The following returns nothing,
```julia
using AutoGrad
y = Param(1.)
f(x) = x
d = @diff f(y)
grad(d, y) # returns nothing
```
while this works:
```julia
f(x) = 1x
d = @diff f(y)
grad(d, y) # returns 1.
```

**Comment by tscode** [comment]
Okay I found another problem with broadcasting of user-defined functions that may be related:
```julia
y = Param([1.,2.])
f(x) = 1x
d = @diff sum(f.(y))
grad(d, y) # returns nothing
```
In contrast, it works with predefined functions:
```julia
d = @diff sum(sin.(y))
grad(d, y) # returns something reasonable
```

**Comment by denizyuret** [comment]
nothing is used interchangably with 0 in AutoGrad results to avoid creating
large 0 arrays.

**Comment by tscode** [comment]
Okay, but I expect the gradient of the identity `x -> x` to be 1, and not 0. So it should not return nothing, if I understood your comment correctly?

**Comment by denizyuret** [comment]
That is correct, I’ll see what’s wrong...

**Comment by denizyuret** [comment]
The first example failed because I did not handle the case where the differentiated function just returns one of the parameter inputs. It should be fixed in the latest master.

The second example failed because AutoGrad does not yet support broadcasting arbitrary functions, only some primitives. I added code that throws an error reflecting this instead of silently failing.
