### ISSUE TITLE
bug second derivative tanh

### ISSUE THREAD

**Issue by CarloLucibello** [denizyuret/AutoGrad.jl#62]
```julia
julia> g1 = grad(tanh)
(::gradfun) (generic function with 1 method)

julia> grad(tanh)(1.) == 1-tanh(1.)^2
true

julia> grad(g1)(2.) #BUG: returns nothing
```

**Comment by CarloLucibello** [comment]
this is still failing on master and julia 0.7

**Comment by denizyuret** [comment]
I found the bug, but now I am trying to understand how it relates to
@MikeInnes's PR.  Basically in the line `og =
r.func(Grad{i},n.outgrad,r.value,r.args...;r.kwargs...)` I should have used
`r` instead of `r.value`.  As soon as I figure out whether there is a
relation to Mike's bug, I will push this.

**Comment by denizyuret** [comment]
Fixed in latest master, please test.

**Comment by CarloLucibello** [comment]
fixed, thanks!
